// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7w6ipyjQWIvQNP03mON8lJXInV9c7vec',
    appId: '1:324005331389:android:44259ae18ff71a43b4d2d4',
    messagingSenderId: '324005331389',
    projectId: 'qt-coach-12d01',
    storageBucket: 'qt-coach-12d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHkGXqRNeiLQ2JCFhzHsuz2slAh8-t2U',
    appId: '1:324005331389:ios:c99e675e2637ccebb4d2d4',
    messagingSenderId: '324005331389',
    projectId: 'qt-coach-12d01',
    storageBucket: 'qt-coach-12d01.firebasestorage.app',
    androidClientId: '324005331389-7ld9m4uvbmevm36hoejrci5q20dpij9b.apps.googleusercontent.com',
    iosClientId: '324005331389-c4bniro22clol1to2pc1bkdatugap89k.apps.googleusercontent.com',
    iosBundleId: 'com.qt.coach',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Mg9BptKeSE2F-WZKipd_hfceclo-_Gw',
    appId: '1:324005331389:web:8cf99594abd89233b4d2d4',
    messagingSenderId: '324005331389',
    projectId: 'qt-coach-12d01',
    authDomain: 'qt-coach-12d01.firebaseapp.com',
    storageBucket: 'qt-coach-12d01.firebasestorage.app',
    measurementId: 'G-HQ1LB3164W',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHkGXqRNeiLQ2JCFhzHsuz2slAh8-t2U',
    appId: '1:324005331389:ios:f57414becc0d9515b4d2d4',
    messagingSenderId: '324005331389',
    projectId: 'qt-coach-12d01',
    storageBucket: 'qt-coach-12d01.firebasestorage.app',
    androidClientId: '324005331389-7ld9m4uvbmevm36hoejrci5q20dpij9b.apps.googleusercontent.com',
    iosBundleId: 'com.qt.qtCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Mg9BptKeSE2F-WZKipd_hfceclo-_Gw',
    appId: '1:324005331389:web:b377b01b9a25dd7bb4d2d4',
    messagingSenderId: '324005331389',
    projectId: 'qt-coach-12d01',
    authDomain: 'qt-coach-12d01.firebaseapp.com',
    storageBucket: 'qt-coach-12d01.firebasestorage.app',
    measurementId: 'G-QYWQJFLM8P',
  );

}